---
scenario:
  name: vagrant-ubuntu

driver:
  name: vagrant
  provider:
    name: virtualbox

platforms:
  - name: instance
    box: ubuntu/xenial64

provisioner:
  name: ansible
  lint:
    name: ansible-lint

lint:
  name: yamllint

verifier:
  name: testinfra
  directory: ../tests/
  lint:
    name: flake8
  options:
    # show which tests where executed in test output
    v: 1
