---
scenario:
  name: docker-ubuntu

driver:
  name: docker

platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu1604}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible
  lint:
    name: ansible-lint

lint:
  name: yamllint

verifier:
  name: testinfra
  lint:
    name: flake8
  options:
    # show which tests where executed in test output
    v: 1
