---
language: python

env:
  global:
    - ROLE_NAME: db
    - secure: "WH7o5IFhjK/zryD/1p6V5BNU07043Tzv14IxNSsgpwRCmSxfoDWOWzNQ0GIznWgBTAGGKjAqfQc69uz/pqa4fiG9wzUEIyHxbVIvGYgxtXj1Sh+jcQ8EvFipmCQ9swjdFKhX6ptw9qnMIorKBnbM5Eaxszw7w81fQFsOLOqUBVw+SgFeIyzPbAY4YRckxCbCykbGMozjsAbimiDfXr9EFYYei6104FPKxjfInuTauZHSCKbwJDIb7KON04uHoC6XH98xqa2xfWqFpA8hLzlhU+vPzL4TEqt4NUovEtKocpr7ICt35G0SMqGYJn0NPdnJRvoB/eu66/H8l7EFSWwJJ2RBlASYhghv2P+idmQwWicvjIqfu8jc1H2XGZc4NV/RN1nXZtqK88ANQXkGJrPgv83jBpkAJO2hRC7sunvXamrvxGfOkMtH1MR/d+JSZP4doe7+V8bWiVR8ncFD+izwQIU53ALn0XW+iPJQ/O8iFIDRXfu33o/tyzqYbSE9RIAnl3GTCj3SOeXQWOPrlr6IHEBDR4axhPWU4qe7rdGw+iQ6z2vP2qIEKgXND5PwQM+mkSs7X1SrBLALlwRwcQvXkASA+bgtZpLw2u4ljtL8Ot5VefxRT6AXxEGE9/5xydONFxRH/v4aAfR0aWXVaD/w8qh8EZ0rLKlaL+olroIPrHE="
    - secure: "WuPoViEdS/PF84+XX7qptTTNxUuqRK77JWvVdu+veCjJ4+kObPyLb9w0pTNItJ1Fn/NVmLuSojLwvCmCBPgT7cbMmRGigBFCpIZDwH0GrGT6rxwK0+gYr/xiSnPK8XYbK/5mwwL6pclgB1zn2LjRRYfX+b51JHqnqfKnh3ZNm/MQv1ABrbm16OlRVyQRgr7y1WS+0foAOAIPqjpGXHvkH2f8DDtyEHkMXEU620+jDenKNy0lS7Mc5Xkrxd1C1mIdQq8mv3+Nk6L4M/LL6cQpVmx+0Q177gw6grgSjJT4cQ84wluZTRpxvTFhJ5sPnVqWSmCES+5jcV/lmPLtZ55CneZluf3X88YBBupXEZEv0OdsFFamwXS18wYcHW/aBJJuKh4396WSEJYiYPC0M9H4f9PseFTHg9bXbj12rfVtZveVpifWsqR6ApySQrmnXEFMFX8iFOgtgjXSGWqjM8HrsiGBCfnm/pIrgy9PA5Fz4PPmr5uFLg/MZtS1GOfj51HBMhQJzwGYriXkC1rQwyMVR6itiq1UGQhU+X/i+zxMPYswl1RRvudVaq8jx5DjUKvXvgjCTPi24mu+grvdbxwfWhDb5QVXazWTSJfyd2K5kEzxtAvY0RcGpJIsAjXgR9EP4WlgEHI6iJFcSiG7S9RckOONkVQBqRXUqcW6wOo6iK0="
    - secure: "Py4CqPNYOs36rxTa/AcicjZ6YdmIvMFA5bBTZFt5sG+kkoSNI0NuwhUhtSkDIwqr+yyorjLw/n8ZROYkAp1vUYU5K1RpZm/wn7xev0TWjXXpWS3sgYwjxA4pjNIZkZqzBgZnkOF5xhxfYlM/2DzmMj7kQwBbISCBF2v9hWFyhj7qdEUDS09lTc5aryODjeeoGoXNTVMYrRec1n0EsSQEfri2kOA8c6uo+vCZylWVbqGoN7GyXp6HpnCYqUZW4gjQJDffBpT48mKj740hrMO2Cve8qpaJNfLEL1CAUkuUw0T/kJm80mZtmTIc/P7rkMwXAhk7RyHmlK8y61/uUyXs+oPJysdBIhtvZghTb9pYmwhg6EchK3rNLp3T+gFtzb81NaObAaeJ8EselqgxFRCDc8GxxTFSsRWs52Xi8RViLiERHhNfhZRL6sWdMMxuRCZ3wZMdpoiu1C+P06DdO0FX+imGJoKwHFjuLZxbXxHolc1SaacpJComHpMh9cGuq23G5W38ioQthZ9bhTHsLgg49bDIv0ZXdvw2kVf5wCzG5WO+FNNzSxmnA+kY/a1lIEo2EFbEyKKIj4tsX4XowOGWz5vTdeLZu3sL6GO82bgTegrmo3OrTu6qdqTy4TQNKgTJZhFC0VA3uSSR76hIiONbUSUfbPrsS1bw/xrrhjdnYME="

before_install:
  - openssl aes-256-cbc -K $encrypted_059a9cadc520_key -iv $encrypted_059a9cadc520_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar -C ~/.ssh

install:
  - pip install molecule apache-libcloud pycrypto

before_script:
  # Use actual role name for project directory
  - ./tests/rename_role_dir.sh

script:
  - molecule --debug test

notifications:
  slack:
    secure: Bt38kzxfQRD6Sj1Q1cHXeKdCs2youdInk0yAbIgi6J6pG9Hpzf+ptZOohEVbvBY0U08d5jj18GQhHMDt0Kkk9On0sYfsGZ/E3Hh6C1knCG5kCjDjWee1TORlK01PRXbfEVH8+9kSI1w04Ic5j78ig5z7AeqGAjKoWUwEpQR5WXGEmczWLR6AbE9sYiRfLo73bHIG7KJCmN3RjMSsOrPyP8v1GLWSvyz1yzxmoW1aYuJArUMOlGhJU/xzjHcKhsnU23IK8gQf+RzzssGY+1izlcIxnA4V0OSqkVeE3ygwBLcH0LUf7CUQ6aOGdzmw3LHPGfgQ+DYbDfXYYReNByQLP04abhuDG7QoE44vIApaMgzIFsM3YndCNNgPBJraZC4XrFNho/sEmu6mE6mrkAJpKU/djbdo91mselQmMop7PsHtZVSRrmsxzvGnP/YDabU1jgA0sA7l2aZpFnv1Gahf5mw5d4HC8tP+GkTGGEVF/Dvnhf/9R4GjK11OsXY21X/VnbX0jSe2+hHkdX0Gh6cNZQk7Ruuh9IuAJ1h3rXy+XIo7lv5qLRMTEbaymxnHdplpKgNQDNK6YwWYZwiYQNsPvtFd3asPBlk5t6gQyOk4x8J4k5MYwakU9V2JP/4IvESPLe1AeUWHe/N/o1mpVM+Hr/ku3DFejOvAEVLizTFgXNM=
