---
language: python
python:
  - '3.6'

env:
  global:
    - MOLECULE_DEBUG: true
    - ROLE_NAME: db
    - GCE_CREDENTIALS_FILE="~/.ssh/credentials.json"
    - GCE_SERVICE_ACCOUNT_EMAIL="travis-ci@infra-219311.iam.gserviceaccount.com"
    - GCE_PROJECT_ID="infra-219311"

before_install:
  - openssl aes-256-cbc -K $encrypted_059a9cadc520_key -iv $encrypted_059a9cadc520_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar -C ~/.ssh

install:
  - pip install molecule apache-libcloud pycrypto

before_script:
  # Use actual role name for project directory
  - ./tests/rename_role_dir.sh

script:
  - molecule lint
  - molecule syntax
  - molecule --debug create
  - molecule test

notifications:
  slack:
    secure: Bt38kzxfQRD6Sj1Q1cHXeKdCs2youdInk0yAbIgi6J6pG9Hpzf+ptZOohEVbvBY0U08d5jj18GQhHMDt0Kkk9On0sYfsGZ/E3Hh6C1knCG5kCjDjWee1TORlK01PRXbfEVH8+9kSI1w04Ic5j78ig5z7AeqGAjKoWUwEpQR5WXGEmczWLR6AbE9sYiRfLo73bHIG7KJCmN3RjMSsOrPyP8v1GLWSvyz1yzxmoW1aYuJArUMOlGhJU/xzjHcKhsnU23IK8gQf+RzzssGY+1izlcIxnA4V0OSqkVeE3ygwBLcH0LUf7CUQ6aOGdzmw3LHPGfgQ+DYbDfXYYReNByQLP04abhuDG7QoE44vIApaMgzIFsM3YndCNNgPBJraZC4XrFNho/sEmu6mE6mrkAJpKU/djbdo91mselQmMop7PsHtZVSRrmsxzvGnP/YDabU1jgA0sA7l2aZpFnv1Gahf5mw5d4HC8tP+GkTGGEVF/Dvnhf/9R4GjK11OsXY21X/VnbX0jSe2+hHkdX0Gh6cNZQk7Ruuh9IuAJ1h3rXy+XIo7lv5qLRMTEbaymxnHdplpKgNQDNK6YwWYZwiYQNsPvtFd3asPBlk5t6gQyOk4x8J4k5MYwakU9V2JP/4IvESPLe1AeUWHe/N/o1mpVM+Hr/ku3DFejOvAEVLizTFgXNM=
