---
language: python

env:
  global:
    - ROLE_NAME: db
    - GCE_CREDENTIALS_FILE="~/.ssh/credentials.json"
    - secure: Kz9JcbJKc5kU5LDaArPBqov/JyeTzbbsAZx3jnkpc9wLVmJYhJ1aGSI1oHgsofKbwxRg8j1CD8neZYzetKCBZ/5zz8XGxQww+Pbtmqk6kAKg+F1WOaAROTIPWjCheVVcPXtavXyILbEFXp4gUYborvL5fP7j/pFTuFXAvhRM6I3E9FNPq53ML3bbqZ4BvcqGTi88Zq1q9kvQhdU0z0NfvCF1oy9xKMG2kBELg508sKSB/MY6a/1MDhzKRizD86Kq5cmK47QQJ5Vhym4Fk7Qmc/hOCaz0OB1Yh4/qY5DS3O1K3M5B5h//sX/x2G1mVY+9CvPURur10wisdS8MO/uXRQF1mzfTIb/FZ6u9vulCrlXIiw0y9q63v+LHJR5KfPUEjDg7/fbpR0bbES3wA6zJU/KAG6panz+NsJIgy5ThL2zzRF+EdlruBIOxRye4ejwQJyge1ZLiE6mUhku4AcQ8BsrGTyE2Ow5B+B3v9BWIT9foyDfcy5gN5LFWoKMkNXQHdseGnhmhk6FS2ZFN5zJLRMIeuJCL6soogC6D5WRrbbej6JtTZEGVSf5O7S6BPX3ZcwrsqEQaOYP4KlSR8pdRpfMLUbWW1c3LTgQU3GyDRYvtYbxv/sXXr9yG3PbnlZADcxgYvN1CTKw0BB0U3H15bbiZz3yvfqmYlqM7D2iYEl8=
    - secure: R+upd8wSxQxas/aiVfIVLPUyOza+iRpEx5XygvMv1DExWayKqRc4Mj9y+GUCuHpvWjNWVblIoquAeI/8/VH6z8pz5Y8MoSbt7wk+TtlxbdRefjjQdcSOPvDAYZuSj7R9ZsoGa4c+1ymbOdA+QImUD7Y+gh1QFaialiK9ETRid2xABGMJ+Wcpzx3VAG4NwQOEP2dORW9c0wrC790mKAIl2bElLlP86mtk4ZJ7LwjTI7XuzKV9SkV1z8D0c3Gix/k+xm1o1t1+LBfLZecq+8Uc6heUXMMd7XAUVXVVrQzEsm8ROD4sBQw1bXL+YzHWrkQHt30tMLRrXmp9TVfWlsnGOFACNMQREAwHiDkjB99vek2q5dvco+tab7KV0IkGfmTfwSfo51qlb8690rTX22yUhiJly6zn28UZsq94ooV+j5v8S69KXJL0nVwBLGMKJ2IhA5NZrnG/WtBfNDYjZiivgPlFZumSi9XkqwasxsixW0UWMsBYtstsisq1cWk8zxLzuZ5YA4pfuoMcm7LCWUQGFRyy+CzBwNdnXMMthKgHCtaqvCpTrH10z+5U3B90twgAbNERKgG9ZEH/xIyobc8qdxWkvwN6ZPBFdr2KN02drwcNsPiXtLMIEMTquzn4IZMZul/J3STu0eylzwhJ0mzSS0zM7let06SqsJvW8CHiZnI=
    - secure: Ynbrh4n+oNjauYYv5macV4EiD59f+mjqyyb2/hh5wpIjq+/61iFPqk38hADleeevfRopBC0KxrLx0+bNa7LgEhPR1nMgOVh5yGlBuYBklBmTHlEXOnpsb1eFmkI0CgCsuZbT/xymE//nS9UF+CYTFE+wOl1hdS7gMLAAMP8xn0Tpo0qPgDG47o92l1v5Ith7W0lCBGquO2iAf/1r7sMV/pZV/vWPF+QSIOPYhWiJEJDtlaKzqNlYVzguacQ7I7UDHZqk3usOTDuhYTzoRIIvnsGUGAJ/CvxgoIHKtaf3QOX9yH/MKDMWDe5dl0PJ4Cdd9XpU7FeybjpXdsO49EFTXx6DwrLERYdzspkiGNP2InGFfUSqQaM5cbYjw2hQzgce3+sFTMaZA7IUtPYVXyptB0qJVXSiEs+n4A0n3pGen0ot4dpvVlpnWPxo5Rq1EkyEJdZW1Bs+SWdiEVGl1IayPZzOQrZnBpo0AZkReU/7A4CmrzIv/QsxCTHBZzux7vsqo1PhoRuMl08fzlOE+laaBtyN2US3yvcE9CtV7NsT6+j+d0pjP88Snq4qwE/IQXz3sakUjlEMvcaLnJ92vdn+4ils4dM2mcaoUJQelR9viehGRRUMwzBOtl7vEIKl8RxMdn6uWhhuie76Xn/y4VRGYqLqs12lwWnVvqLfJ51Xlmg=
  matrix:
    - MOLECULE_DISTRO: ubuntu1604

before_install:
  - openssl aes-256-cbc -K $encrypted_059a9cadc520_key -iv $encrypted_059a9cadc520_iv
    -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar -C ~/.ssh
  - chmod 0600 ~/.ssh/gce_rsa_key

install:
  - pip install molecule apache-libcloud

before_script:
  # Use actual role name for project directory
  - ./tests/rename_role_dir.sh

script:
  - molecule test

notifications:
  slack:
    secure: Bt38kzxfQRD6Sj1Q1cHXeKdCs2youdInk0yAbIgi6J6pG9Hpzf+ptZOohEVbvBY0U08d5jj18GQhHMDt0Kkk9On0sYfsGZ/E3Hh6C1knCG5kCjDjWee1TORlK01PRXbfEVH8+9kSI1w04Ic5j78ig5z7AeqGAjKoWUwEpQR5WXGEmczWLR6AbE9sYiRfLo73bHIG7KJCmN3RjMSsOrPyP8v1GLWSvyz1yzxmoW1aYuJArUMOlGhJU/xzjHcKhsnU23IK8gQf+RzzssGY+1izlcIxnA4V0OSqkVeE3ygwBLcH0LUf7CUQ6aOGdzmw3LHPGfgQ+DYbDfXYYReNByQLP04abhuDG7QoE44vIApaMgzIFsM3YndCNNgPBJraZC4XrFNho/sEmu6mE6mrkAJpKU/djbdo91mselQmMop7PsHtZVSRrmsxzvGnP/YDabU1jgA0sA7l2aZpFnv1Gahf5mw5d4HC8tP+GkTGGEVF/Dvnhf/9R4GjK11OsXY21X/VnbX0jSe2+hHkdX0Gh6cNZQk7Ruuh9IuAJ1h3rXy+XIo7lv5qLRMTEbaymxnHdplpKgNQDNK6YwWYZwiYQNsPvtFd3asPBlk5t6gQyOk4x8J4k5MYwakU9V2JP/4IvESPLe1AeUWHe/N/o1mpVM+Hr/ku3DFejOvAEVLizTFgXNM=
