---
- name: Add APT key
  apt_key:
    id: 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5
    keyserver: keyserver.ubuntu.com
  tags: install

- name: Add APT repository
  apt_repository:
    repo: deb [ arch=amd64 ] http://repo.mongodb.org/apt/ubuntu  {{ ansible_lsb.codename }}/mongodb-org/3.6 multiverse
    state: present
  tags: install

- name: Install mongodb package
  apt:
    name: mongodb-org
    state: present
  tags: install

- name: Configure service supervisor
  systemd:
    name: mongod
    enabled: true
    state: started
  tags: install
